# Generated by Django 5.1.7 on 2025-03-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0002_event_player_ranking_delete_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='NumMaximums',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='NumRankingTitles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
