# Generated by Django 5.1.7 on 2025-03-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneFourSeven', '0005_rename_url_upcomingmatch_detailsurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingmatch',
            name='FrameScores',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='upcomingmatch',
            name='OnBreak',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upcomingmatch',
            name='Score1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upcomingmatch',
            name='Score2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
